### ISSUE TITLE
Documentation to use the library?

### ISSUE THREAD

**Issue by sterichards** [r-everse/linkedin-php#1]
Hi,

I'm seeing documentation that shows how to authenticate against Linkedin V2. Are there any examples you could post that will show how a post to LinkedIn API is made?

**Comment by giovannialbero1992** [comment]
Hi @sterichards, thank you for your interest in our library 😄 .
I share here a snippet with an example to share an existing post on LinkedIn, let me know if it is ok so I'll push it on `README.md` file.
```php
$client = new Client('appId', 'appSecret', 'returnUrl');
if ($_GET['code']) {
    $client->initToken($_GET['code']);
    
    $shares = new Shares();
    $shares->setResharedShare('urn:li:share:1232132') // Post's urn:id
    
    $shares->setOwner('urn:li:person:c7RFYxyz78')
    
    $shareText = new ShareText();
    $shareText->setTitle('my title');
    
    $shares->setText($shareText);
    
    $shareEndpoint = new REverse\LinkedIn\Endpoint\Share($client);
    $shareEndpoint->postShares($shares);
} else {
    $authUrl = $client->getAuthorizationUrl([
        'scope' => [Client::PERMISSION_LITE_PROFILE, Client::PERMISSION_W_MEMBER_SOCIAL]
    ]);
    header('Location: '.$authUrl);
    exit;
}
```

Before to perform this operation, the user must be authenticated to application.

**Comment by sterichards** [comment]
I hadn't been notified about your initial swift response sorry

I have since written the V2 calls manually using Guzzle, which support text and/or image sharing to V2

I can share that code with you if it's of any use to use

**Comment by giovannialbero1992** [comment]
@sterichards don't worry 😄 
I've pushed the example above in the readme file.
The support for image it should be already implemented. If you want you can try to use our library.
There are three classes to manage images: `ShareContent`, `ContentEntity`, `Thumbnail`. To use it you only declare the classes in the main class `Shares` and pass it to endpoint.
