### ISSUE TITLE
Undefined index: code

### ISSUE THREAD

**Issue by packytagliaferro** [r-everse/linkedin-php#2]
There isnt a lot of docs for this package but I used the demo code with my app with my linkedn app ID, Secret and the current URL for the callback. 

I get the error `Undefined index: code`. 

I imagine it because there is no `code` parameter in the url. Is this supposed to redirect me to the callback URL?

**Comment by giovannialbero1992** [comment]
Hi @packytagliaferro thank you for your interest to our library :smiley: .
Can you share your code with us?
Is the error returned by the library or by LinkedIn?

**Comment by packytagliaferro** [comment]
The error is from my controller. So this is what I have:

web route:
`Route::get('/linkedin', 'PostController@linkedin');
`
PostController:

```
 public function linkedin()
    {
        $client = new Client(env('LINKEDIN_ID'), env('LINKEDIN_SECRET'), 'http://community.test/linkedin');
        if ($_GET['code']) {
            $client->initToken($_GET['code']);

            $me = new Me($client);
        } else {
            $authUrl = $client->getAuthorizationUrl([
                'scope' => [Client::PERMISSION_LITE_PROFILE]
            ]);
            header('Location: ' . $authUrl);
            exit;
        }
    }
```

**Comment by giovannialbero1992** [comment]
@packytagliaferro you should verify that key exists before.
```php
if(array_key_exists('code', $_GET)) { ... }
```

**Comment by packytagliaferro** [comment]
@giovannialbero1992 Okay, I added that but the original code is straight from your docs (just a heads up, might want to change that as well). Now I get the error:

`Call to undefined method REverse\LinkedIn\Client::getAuthorizationUrl()
`
Which would be from your library

**Comment by giovannialbero1992** [comment]
Thanks for your hint @packytagliaferro 😃 
I've updated documentation to fix the if condition and fixed the bad call on Client class.

Let me know.
Thanks!

**Comment by giovannialbero1992** [comment]
@packytagliaferro is it all ok? Do you be able to try the library?
