### ISSUE TITLE
Possible to share the image?

### ISSUE THREAD

**Issue by sandisahdewo** [r-everse/linkedin-php#4]
Hey there,

are this package support the image share or upload image to post?
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin/consumer/context#create-an-image-share

**Comment by ddonnini** [comment]
Well, no. There is no plan on developing any feature right now, are you interested in developing this one?

**Comment by giovannialbero1992** [comment]
Ehy @sandisahdewo you can see something useful for your purpose here: https://github.com/SMarTStrategy/linkedin-php/blob/php-7/lib/LinkedIn/Endpoint/AssetsRegisterUpload.php

**Comment by ddonnini** [comment]
Ah wow! Well it seems like your repo is evolving compare to this, maybe we should tag this repo as discontinued and point forward yours @giovannialbero1992, what do you think?

**Comment by sandisahdewo** [comment]
Thanks guys!
I found another repo that also supports Laravel: https://github.com/Light-it-labs/laravel-linkedin-share
but yeah, it still needs customization for authentication.

**Comment by dborsatto** [comment]
Closing this as this library is no longer actively developed.
